### ISSUE TITLE
auto naming param in cases of function declaration and named argument

### ISSUE THREAD

**Issue by lyrachord** [Kotlin/KEEP#101]
code it: 
<1>
```java
functionX(ClassReader, int offset, InputStream){
    x = classReader.getItem(offset)
    y = inputStream.read(conversion(x))
}
```

Rule: just lowercase the first char of the type name, except primitive which maybe too naive

Reason: in most java methods people use redundant duplication style, not convenient to write and to read

<2>
```kotlin
functionx(....){
normalizeCase = readConfig(...)
... //other arguments
//now kotlin codes do:
reformat(str,
    normalizeCase = normalizeCase,  //weird
    upperCaseFirstLetter = true,
    divideByCamelHumps = false,
    wordSeparator = '_'
)
//because local name same as param name, it can be ignore
//after new auto-name-match
reformat(str,
    normalizeCase,
    upperCaseFirstLetter,
    divideByCamelHumps,
    wordSeparator
)
}
````
Rule: auto match and connect local name to argument name
Reason: avoid to be weird and duplication

Both features in my language(C-family-style), it looks good. 

Match both position and name in kotlin should not hard.

BTW I doubt auto naming scheme affect reading preference in pascal style(name:type)

**Comment by elizarov** [comment]
I'm closing this issue. If you still have interest in this design enhancement and specific use-cases where it would be helpful, then please submit an issue to https://kotl.in/issue under the "Languge Design" subsystem.
