### ISSUE TITLE
Functional types with big arity on JVM

### ISSUE THREAD

**Issue by udalov** [Kotlin/KEEP#107]
Discussion of the proposal: https://github.com/Kotlin/KEEP/blob/master/proposals/functional-types-with-big-arity-on-jvm.md

**Comment by erokhins** [comment]
Why do not use this declaration for FuncitonN:
```
interface FunctionN<in P0, in P1, ... in P21, out R> : Function<R> {
   operator fun invoke(p0: P0, p1: P1, ... p21: P21, vararg others: Any?): R
   override val arity: Int 
}
```

Also from this proposal it isn't clear how we use arity variable declared inside our `FunctionN`. Seems like section about type checks and cast are missing.

If FunctionN declared in java without Arity annotation, we get some type that isn't related to normal function types and value of such type cannot be passed to function with some function parameter. It is correct?

By the way if java implement some kotlin interface with some function parameter with 42 parameters, then we have enough information to calculate correct arity for FunctionN comes from java. Moreover there is only way to create correct fake-override for this case.

**Comment by udalov** [comment]
@erokhins 
> Why do not use this declaration for FuncitonN:
> 
> ```
> interface FunctionN<in P0, in P1, ... in P21, out R> : Function<R> {
>    operator fun invoke(p0: P0, p1: P1, ... p21: P21, vararg others: Any?): R
>    override val arity: Int 
> }
> ```

I like the `invoke(vararg args: Any?)` approach a little more because it's more general. For example, (if we need this) we can support `FunctionN` even for smaller numbers of parameters in the future. Also, the implementation is simpler.

Are there any major benefits of this new scheme?

---

> Also from this proposal it isn't clear how we use arity variable declared inside our `FunctionN`. Seems like section about type checks and cast are missing.

Basically `is`/`as` on functional types works via an internal runtime function which calls `arity`, and this is done already since Kotlin 1.0, so nothing will change here. I'll add a note about it.

---

> If FunctionN declared in java without Arity annotation, we get some type that isn't related to normal function types and value of such type cannot be passed to function with some function parameter. It is correct?

Yes, as described in the proposal:
> In case no `Arity` annotation is provided, the `FunctionN` type will be loaded simply as the “foreign” `FunctionN` type and not as a true Kotlin functional type. It's the responsibility of the user to provide the correct value in the `Arity` annotation <...>

---

> By the way if java implement some kotlin interface with some function parameter with 42 parameters, then we have enough information to calculate correct arity for FunctionN comes from java. Moreover there is only way to create correct fake-override for this case.

I don't know how to do this in this case, so not sure if it's worth it overall:
```
// FILE: I.kt
interface I {
    fun foo(f: (Any?, Any?, ..., Any?) -> Any?)
}

// FILE: J.java
public interface J extends I {
    // Is it an override, or a new method that takes `FunctionN`?
    // Maybe the user meant a new method that takes function of another arity here,
    // but forgot to specify @Arity?
    public void foo(FunctionN f);
}
```

**Comment by erokhins** [comment]
> Are there any major benefits of this new scheme?
Not sure that is major benefit, but part of generic signature becomes available from java in new scheme.

>I don't know how to do this in this case, so not sure if it's worth it overall:
>```
>// FILE: I.kt
>interface I {
>    fun foo(f: (Any?, Any?, ..., Any?) -> Any?)
>}
>
>// FILE: J.java
>public interface J extends I {
>   // Is it an override, or a new method that takes `FunctionN`?
>    // Maybe the user meant a new method that takes function of another arity here,
>    // but forgot to specify @Arity?
>    public void foo(FunctionN f);
>}
>```
In this case it is clear that it is an override, because jvm signature for base method and this one is the same. So it isn't possible to override it via different way.

Ouch. It is a big problem.
```
fun foo(f: (Any, Any, ... Any) -> Unit) {} // 42 Any
fun foo(f: (Any, Any, ... Any, Any) -> Unit) {} // 43 Any
```
In this example jvm signatures for this methods the same, and error will be reported :(

**Comment by udalov** [comment]
> ```
> fun foo(f: (Any, Any, ... Any) -> Unit) {} // 42 Any
> fun foo(f: (Any, Any, ... Any, Any) -> Unit) {} // 43 Any
> ```
> In this example jvm signatures for this methods the same, and error will be reported :(

I don't think it's a big problem. One can always use `@JvmName` as a workaround.

**Comment by cbruegg** [comment]
There's no word on performance in the proposal. Would wrapping the parameters in an array come at a cost?

**Comment by udalov** [comment]
@kenzierocks I'm not sure how do you propose to perform argument checking in `#from`, could you please elaborate?

Also `java.util.function.Function` requires JDK 1.8, while `kotlin-stdlib` builds against JDK 1.6.

**Comment by kenzierocks** [comment]
I was thinking a method like this:
```kotlin
interface FunctionN ... {
    companion object {
        fun <R> from(arity: Int, body: (Array<out Any?>) -> R): FunctionN<R> {
            return object : FunctionN<R> {
                override fun invoke(vararg args: Any?): R {
                    if (args.size != arity) {
                        // maybe include expected/actual arity in error:
                        throw IllegalArgumentException("Wrong number of arguments.");
                    }
                    return body(args)
                }
                override val arity = arity
            }
        }
    }
}
```

Kotlin usage (example, not for actual usage since the type isn't used in Kotlin):
```kotlin
val print5 = FunctionN.from(5) { args -> println("The 5 args: ${args.map{it}}") }
print5("a", "b", "c", "d", "e")
print5("a", "b", "c", "d", "e", "f") // throws error
```

Java (8) usage (untested, but I think it should work):
```java
FunctionN<Unit> print5 = FunctionN.from(5, (args) -> System.out.println(Arrays.toString(args)));
print5.invoke("a", "b", "c", "d", "e")
print5.invoke("a", "b", "c", "d", "e", "f") // throws error
```

RE: JDK requirements, I used `j.u.f.Function` as a stand-in, I think accepting a `Function1` would work as well (as done above), which is part of the stdlib.

This new function would help people create semantically valid `FunctionN` instances in Java, as well as provide a much simpler method of creating them in Java 8+.

**Comment by udalov** [comment]
Thanks for the explanation, this is a very nice suggestion. Alternatively, we could expose a class `FunctionNImpl` which takes arity and a function block in the constructor, but your way is probably better if we need to change implementation incompatibly in the future.

I've reported this idea as [KT-27038](https://youtrack.jetbrains.com/issue/KT-27038). Thanks!

**Comment by elizarov** [comment]
Closing this issue, as the proposal was implemented a while ago and merged.
