### ISSUE TITLE
Companion values

### ISSUE THREAD

**Issue by sakno** [Kotlin/KEEP#114]
Discussion of the proposal: #106 
> **Summary**
This proposal provides ability to declare companion `val` or `var` and expose implicit visibility of all members associated with type specified in the declaration. This case extends `companion` behavior at instance level rather than at class level in contrast with `companion object` declaration.

**Comment by fatjoem** [comment]
I like the idea but I don't like the usage of keyword "companion" for this. 

The proposal adds a feature to classes that already exists for functions: For functions this feature is called "extension function".

Indeed, with this proposal every function in the class implicitly becomes an extension function, whose extension receiver is implicitly provided.

Hence I would propose to rename this proposal "extension values" and use a new "extension" keyword:

extension val a: Context = ...

All functions in a class that has such property would implicitly become an extension function whose receiver would be implicitly set to a.

The JVM language Xtend has a very similar feature and they also use a similar keyword for this (extend or extension).
