### ISSUE TITLE
Automatic invocation of operator invoke 

### ISSUE THREAD

**Issue by neonailol** [Kotlin/KEEP#116]
Kotlin has a great feature to overload invoke operator.
It would be nice to have a compiler automatically deduce when it can be called in an unambiguous way.

Most generic example:

```kotlin
class IsBlank(private val origin: String) {
    fun invoke(): Boolean = origin.isBlank()
}
```
currently, there a two ways to get boolean value from this:
```kotlin
if (IsBlank("").invoke()) { }
if (IsBlank("")())) { }
```
it would be nice for a compiler to deduce that invoke operator and use it implicitly, so this would work
```kotlin
if (IsBlank("")) { }
```
Is this feaure worth a proposal, or this idea is not worth the time?

**Comment by aouerfelli** [comment]
But what if you don't want to invoke it after constructing it? If you want to invoke it automatically, then using a function instead of a class makes more sense.
I think what you're after is something like a conditional operator function, where if you pass in an object to a conditional statement (`if`, `while`), it calls the conditional operator function on that object. Personally, I don't think it's viable enough, but it might be worth a shot.

**Comment by neonailol** [comment]
No, conditional statements here are only to illustrate the idea, 
I am working on a library with oop primitives and lazy evaluation, and I have this code in a test:

```kotlin
        assertEquals(
            AvgOf(
                { MinOf(1.0, 2.0).invoke() },
                { MaxOf(2.0, 4.0).invoke() },
                { SumOf(1.0, 2.0, 2.0).invoke() },
                {
                    Ternary(
                        true,
                        { 5.0 },
                        { 1.0 }
                    ).invoke().invoke()
                }
            ).toInt(),
            3
        )
```

`AvgOf` takes lambdas of type `() -> Number`
`MinOf`, `MaxOf`, `SumOf` returns Double in the invoke method
`Ternary` takes a condition and two possible outcomes, in this case, they are `() -> Double`, so on first invoke it returns  `() -> Double` and on a second invoke it returns `Double`

And I think the compiler can actually detect all these calls in some cases, and do them for me.

I know that for this particular case, all of them could probably implement `Number`, but this out of the scope of the original idea, and do not work currently when compiled to js, due to bug `KT-17345`

**Comment by PCasafont** [comment]
Wouldn't your use case work in a much better fashion if it was functional-oriented? Why are you using objects for that purpose in the first place?

**Comment by fvasco** [comment]
@neonailol 
> I am working on a library with oop primitives and lazy evaluation

You can implement the [`Lazy`](http://kotlinlang.org/api/latest/jvm/stdlib/kotlin/-lazy/index.html) interface instead of using the `invoke` operator.

**Comment by elizarov** [comment]
The value of this feature is not clear. If you have a specific use-case, please create an issue at https://kotl.in/issue
