### ISSUE TITLE
Coding Conventions of Extension names

### ISSUE THREAD

**Issue by xiaoxiangmoe** [Kotlin/KEEP#117]
#### EXTENSION_SHADOWED_BY_MEMBER

If a class has a member function, and an extension function is defined which has the same receiver type, the same name and is applicable to given arguments, the member always wins. This may cause trouble in the future. The extension code that can run is not not compatible with the new version of library that implements a member function with same name.

#### Same author's Extension

If we define a extension functions/properties for the library we write, use the name start with a lower case letter and use camel humps and no underscores.

``` kotlin
class C {
}

// the same author wrote the foo extension
fun C.fooBar() { println("same author's extension") }
```

#### Third-party Extension

If we define a extension functions/properties for the library we can't control, use the name start with a underscore followed by a lower case letter and use camel humps and no underscores.

``` kotlin
class C {
    fun fooBar() { println("member") }
}

// third-part extension's name should start with underscore
fun C._fooBar() { println("third-part extension") }
```

**Comment by ice1000** [comment]
The stdlib has already got a lot of extensions not started with `_`. This proposal sounds very weird...

**Comment by xiaoxiangmoe** [comment]
@ice1000 The conflict between extension and member is still an existing problem. If we do not resolve 
 the problem from the naming, we can only solve it from the grammar.

**Comment by elizarov** [comment]
The KEEP issue tracker is a repository for Kotlin design proposals. Please, see https://github.com/Kotlin/KEEP/blob/master/README.md
