### ISSUE TITLE
java.lang.LinkageError: writeToParcel overrides final method in Super Class

### ISSUE THREAD

**Issue by rishabh876** [Kotlin/KEEP#119]
I have Two classes `Bank` And `BankAccount`. `BankAccount` extends `Bank` class. Both have `@Parcelize` implementaton but when I run my code I get this error.

```java.lang.LinkageError: Method void com.myapp.ui.otm.dataModel.BankAccount.writeToParcel(android.os.Parcel, int) overrides final method in class Lcom/myapp/ui/otm/dataModel/Bank; (declaration of 'com.myapp.ui.otm.dataModel.BankAccount' appears in /data/app/com.myapp-1/base.apk:classes2.dex)```

What should I do?

**Comment by JakeWharton** [comment]
File a bug at http://kotl.in/issue.

**Comment by yterletskyi** [comment]
is there a fix please?

**Comment by rishabh876** [comment]
@yterletskyi This is has been fixed in newer version of kotlin 
https://youtrack.jetbrains.com/issue/KT-24720
