### ISSUE TITLE
Local variable declaration in 'when' subject

### ISSUE THREAD

**Issue by dnpetrov** [Kotlin/KEEP#120]
Discussion of the proposal in #121 
(this is a placeholder issue for 'val' in 'when' subject discussion)

**Comment by fvasco** [comment]
The proposal works also if you strip the `val` keyword, similar to method's parameter declaration.

```
when ( x = foo() ) { ... }
when ( x :Number = foo() ) { ... }
```

instead of


```
when ( val x = foo() ) { ... }
when ( val x :Number = foo() ) { ... }
```

---
Generally you should use *must* instead of *should*

```
when (var x = foo() { ... }             // Error, should be a val
when (var x = foo() { ... }             // Error, must be a val
```

**Comment by gildor** [comment]
> The proposal works also if you strip the val keyword, 
I think that for this case I would prefer yo use val syntax, just because it closer to local function definition and because `foo = foo()` looks too similar to `foo == foo()` that also valid expression with completely different semantics

**Comment by fvasco** [comment]
However the proposal looks strange, the variable declaration is dissimilar to `for each`, moreover `when` requires an expression while `val x = ...` is a statement.

> `foo = foo()` looks too similar to `foo == foo()`

You are right, it is terrible!

**Comment by dnpetrov** [comment]
Difference between `for` and `when` is that `for` always declares a variable, and `when` doesn't. There's a form with subject expression. Explicit `val` keyword here makes code easier to read, otherwise it looks like an expression (or, even worse, an assignment statement to an undeclared variable).

**Comment by ktkit** [comment]
I believe the way most consistent with current Kotlin semantic is using a context variable, so-called arrow or it-style:
```kotlin
when ( foo() ) { 
  is Int -> "foo is $it"
  else -> "otherwise"
}

when ( foo() ) { v ->
  is Int -> "foo is $v"
  else -> "otherwise"
}
```
The alternative with prefixing val keyword: `when ( val x = foo() ) { ... }` implies that now in Kotlin value assignmant returns a value too: `if (val x  =  foo()) { ... }`, or even `var x = false; if (x  =  foo()) { ... }`. Like in Java.

**Comment by dnpetrov** [comment]
@ktkit 
`when` subject can't be referred by an implicit `it` variable, since it would be a breaking change (consider a `when` expression in a lambda).

**Comment by dnpetrov** [comment]
@edenman 
Doesn't make much sense unless multiple statements (separated by semicolon) are allowed in the `if` condition (or in the `when` subject). E.g.,
```
if (val x = foo(); x != null) { ... }
```
We've discussed such syntax internally, and decided that it's ok to introduce it later (and treat `when (val x = foo())` as a short-hand form for `when (val x = foo(); x)`).

**Comment by dnpetrov** [comment]
@fvasco 
This would require some non-trivial scoping rules for variables declared in val-expressions; e.g.,  `foo(bar(val x = qux()), x)`. Looks like another can of worms I'd personally prefer not to care about at the moment.

**Comment by ephemient** [comment]
> @edenman
> Doesn't make much sense unless multiple statements (separated by semicolon) are allowed in the `if` condition (or in the `when` subject). E.g.,
> 
> ```
> if (val x = foo(); x != null) { ... }
> ```
> We've discussed such syntax internally, and decided that it's ok to introduce it later (and treat `when (val x = foo())` as a short-hand form for `when (val x = foo(); x)`).

I assume this would include `while` and `do-while`, as in

    while (val line = getLine(); line.isNotEmpty())

Is #120 also for this future work or is there another issue?

**Comment by dnpetrov** [comment]
> I assume this would include `while` and `do-while`, as in
> 
> ```
> while (val line = getLine(); line.isNotEmpty())
> ```
> Is #120 also for this future work or is there another issue?

No KEEP yet. See:
https://youtrack.jetbrains.com/issue/KT-25765
https://youtrack.jetbrains.com/issue/KT-25698
