### ISSUE TITLE
Seperate @Parcelize from findViewById generation into seperate plugins

### ISSUE THREAD

**Issue by AdityaAnand1** [Kotlin/KEEP#126]
I keep finding random view ids being suggested in auto complete in utterly random situations. 

* As someone who re-uses a lot of IDs (e.g. "toolbar" everywhere, instead of "main_toolbar", "profile_toolbar") the findViewById replacement offered by android extensions is of no use to me. It's actually quite a hindrance since I have to carefully sift through my code to ensure some random view ID isn't being used somewhere since it's so easy to accidentally import.
* As someone working on a legacy project with an immense number of layouts, the migration to kotlin-android-extensions way of finding views is not trivial (=> Not arguing about it's usefulness, but it's appropriateness in some circumstances) and
* Quite unnecessary as I'm using data binding which already gives me views in a format like`ui.toolbar` in a near little package so I do not want the overhead of kotlin-android-extensions (as useful as it might be in other use-cases) generating so much stuff for every single layout in my project when databinding is also doing the exact same thing.

Although, I still want @Parcelize. I just want it without view id generation stuff. Considering that these are both entirely separate unique functionalities, it does not make sense to bundle them together anyways. They should be separated.

**Comment by JakeWharton** [comment]
This is not a KEEP. Please file generate feature requests to http://kotl.in/issue

**Comment by AdityaAnand1** [comment]
https://youtrack.jetbrains.com/issue/KT-25280
