### ISSUE TITLE
Extensions to copy maps

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/KEEP#13]
Discussions about the [Extensions to copy maps](../blob/master/proposals/stdlib/map-copying.md) will be held here.

**Comment by voddan** [comment]
There is an empty cell in the reference table for `Iterable<Pair<K, V>>.toMutableMap(): MutableMap<K, V>`. There is a similar function for an immutable map `Iterable<Pair<K, V>>.toMap(): Map<K, V>`. Would not it be logical to introduce the mutable one?

**Comment by ilya-g** [comment]
@voddan  `Iterable<Pair<K, V>>.toMap(destination: M)` covers that case and it seems to be required not so often. We have it in the "future advancements" section :)

**Comment by binkley** [comment]
I'm glad there's a `toMutableMap`, `toMap`, etc.  Disappointed there is not a simple `copy` which knows the map type and "does the right thing" (akin to JDK `clone` without the downsides).

**Comment by ilya-g** [comment]
@binkley This is not possible in general case, see the discussion in this issue: [KT-11221](https://youtrack.jetbrains.com/issue/KT-11221)
