### ISSUE TITLE
Smart function overloading.

### ISSUE THREAD

**Issue by Cybermaxke** [Kotlin/KEEP#133]
I was experimenting by extending SLF4J `Logger` classes to support logging lazily constructed `String`s and `Text` objects (which is text with colors).

Let's say I have the following extension functions:
```kotlin
fun Logger.debug(fn: () -> String) {
    if (isDebugEnabled) debug(fn())
}

@JvmName("debugText")
fun Logger.debug(fn: () -> Text) {
    if (isDebugEnabled) debug(fn().toPlain())
}
```
Due the same signatures in bytecode I added a `@JvmName` to the text method.

However, after trying to call the methods I found out that this is also a problem for Kotlin, it does not know which function to target:
```kotlin
fun test() {
    val logger: Logger = getLogger()
    logger.debug { "Test" }
}
```
It's clear that I am trying to call the function with the `String` and not `Text`. It would be nice if this is possible in Kotlin.

Right now I am just using `Any` instead, but it's not optimal.

**Comment by ilya-g** [comment]
Since this doesn't qualify as a proposal, I'm going to close it here. The status can be tracked in the issue mentioned above.
