### ISSUE TITLE
@Parcelize cannot be used with `readTypedArray` and `readTypedList` methods

### ISSUE THREAD

**Issue by Zhuinden** [Kotlin/KEEP#145]
See https://stackoverflow.com/questions/51799353/how-to-use-parcel-readtypedlist-along-with-parcelize-from-kotlin-android-exte

These functions require the CREATOR of the type, however `@Parcelize` annotated classes do not have a CREATOR field that is accessible for the user.

Therefore `@Parcelize` cannot be used with `readTypedList()` and `readTypedArray()`.

This is a limitation that is quite a hindrance in the sense that the only way to avoid it is to not use `@Parcelize` on classes that are used in typed lists, OR save the list as ArrayList using `writeSerializable` instead.

**Comment by JakeWharton** [comment]
Bugs for Kotlin features go on https://youtrack.jetbrains.com/issues/KT. This one is already reported at https://youtrack.jetbrains.com/issue/KT-19853.

**Comment by Zhuinden** [comment]
D'oh my mistake, I'll take my rambling over there, thanks 👍
