### ISSUE TITLE
Enhancing main entry point convention

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/KEEP#158]
Proposal: https://github.com/Kotlin/KEEP/blob/enhancing-main-convention/proposals/enhancing-main-convention.md

PR for comments: #157

**Comment by Dico200** [comment]
from `runSuspend` definition for JVM:

> `override fun resumeWith(result: Result<Unit>) = synchronized(this) {`

If there isn't a typealias for `Result` to `SuccessOrFailure` somewhere, I'm convinced the type should be `SuccessOrFailure<Unit>`.

**Comment by hannespernpeintner** [comment]
@dzharkov Wow, that's a step! Is there any info about this step somewhere!? I'm just interested in the topic after I followed the discussion about the naming of SuccessOrFailure/Result.

**Comment by elizarov** [comment]
@hannespernpeintner 
> Wow, that's a step! Is there any info about this step somewhere!? I'm just interested in the topic after I followed the discussion about the naming of SuccessOrFailure/Result.
Please watch updates in the corresponding KEEP. It will be updated: https://github.com/Kotlin/KEEP/issues/127

**Comment by gildor** [comment]
If there are problems with suspend implementation on Kotlin Native, maybe we could support at least part of new convention: omit args from main function

**Comment by dzharkov** [comment]
@gildor 

> If there are problems with suspend implementation on Kotlin Native, maybe we could support at least part of new convention: omit args from main function

I think at some point they will be supported

**Comment by dzharkov** [comment]
> @dzharkov
> I read all the discussion in KEEP #127 just days ago, checked back there now and I don't see any updates, nor in the file. I do not see anything conclusively saying that the decision was revisited.
> 
> So as far as I understand it, it's a change you intend to make - which has yet to be mentioned in the KEEP.
> Which is fair enough, I just wanted to point out I don't recall such a decision being made.

Finally, it's here
https://github.com/Kotlin/KEEP/issues/127#issuecomment-423065507

**Comment by dzharkov** [comment]
Implemented in 1.3
