### ISSUE TITLE
JS - class type at runtime

### ISSUE THREAD

**Issue by danfma** [Kotlin/KEEP#16]
# Ability to retrieve the type of a class at runtime

## Use cases / motivation

- Some libraries, like React, Aurelia, Angular, sometimes require that you pass a class type as parameter to a function or other configuration place;
- React uses this to define each component type;
- Dependency injection libraries can use the type to instantiate instances;

## Proposed solution

A simple function named `typeOf` or `classOf` which retrieves the type of a class.

## Actual code workaround

By following one idea of @bashor, I created this method at (https://github.com/danfma/kotlinjs-runtime-extension/blob/master/src/kotlin/runtime/extension/typeOf.kt) which grabs the type of `T` and retrieve its class (function declaration).

```kotlin
inline fun <reified T> typeOf(): Type<T> {
    var type: Type<T>? = null

    js("var tmp = Kotlin.isType; Kotlin.isType = function(a, b) { type = b }")

    null is T

    js("Kotlin.isType = tmp;")

    return type!!
}
```

But the code could be broken in any future update, so we need a more concrete way.

## Examples of use.

```kotlin 
val carType = typeOf<Car>()
```

* https://github.com/danfma/kotlinjs-react/blob/master/src/react/core/functions.kt
* https://github.com/danfma/kotlinjs-runtime-extension/blob/master/src/kotlin/runtime/extension/container/Container.kt

**Comment by bashor** [comment]
I think it should be covered by `Car::class` which should be implemented as part of lightweight reflection (based on JS capabilities)

**Comment by danfma** [comment]
Fine to me.

**Comment by bashor** [comment]
Actually, it's already fixed. Now you can write `Car::class.js` or `jsClass<Car>()`. Note first is preferred since second will be deprecated and removed later.
