### ISSUE TITLE
Allow the use of @JvmOverloads in interface methods

### ISSUE THREAD

**Issue by adam-arold** [Kotlin/KEEP#162]
Kotlin supports having default values for parameters in functions right now:

```kotlin
interface Drawable {

   fun drawOnto(surface: DrawSurface, position: Position = Position.zero())

}
```

This way the function can be called with either just the first, or both parameters supplied.

The problem is that Java doesn't support default values so it looks like a good idea to allow having `@JvmOverloads` on functions like this to improve interoperability with Java:

```kotiln
interface Drawable {

    @JvmOverloads
    fun drawOnto(surface: DrawSurface, position: Position = Position.zero())
}
```

Right now if I do this I get the following error:

> '@JvmOverloads' annotation cannot be used on interface methods

There is a workaround, but it involves some manual work:

```kotlin
interface Drawable {

    fun drawOnto(surface: DrawSurface) {
        drawOnto(surface, Position.defaultPosition())
    }

    fun drawOnto(surface: DrawSurface, position: Position)
}
```

I suggest allowing the usage of `@JvmOverloads` for interface functions.

**Comment by gildor** [comment]
This is not proper KEEP
Please check https://github.com/Kotlin/KEEP#how-to-propose
Also, you can check other issues in this repo to see how KEEP process works

**Comment by adam-arold** [comment]
I checked that document but it does not detail how to propose. It says:

> If you only have a vague feature idea, please share it in the #language-proposals channel in our public Slack (get invite here), or in the Forum's Language design category.

but it does not say what I should do if I have a *concrete* idea. Can you point me to a proper source in how a KEEP Issue should look like?

**Comment by adam-arold** [comment]
I also asked for Slack access as suggested days ago but I got no response yet.

**Comment by gildor** [comment]
First of all you should create PR with proposal document and use this issue only for discussion, you can see examples of proposals in Pull Request sections

Also you wrote `Would it make sense to implement this?`, does it mean that you are not sure yourself?Because proposal should provide rationale why this feature is useful, compare with existing solutions, provide some implementation details

**Comment by adam-arold** [comment]
Okay, I'll peruse the proposal documents!

**Comment by elizarov** [comment]
I'm closing this issue since it does not present an implementation design (see https://github.com/Kotlin/KEEP/blob/master/README.md) Please, follow and vote for the corresponding YT issue: https://youtrack.jetbrains.com/issue/KT-36102 It would be helpful to see more use-cases there.
