### ISSUE TITLE
Adding "->" operator as an alternative to ":"

### ISSUE THREAD

**Issue by Andru1999** [Kotlin/KEEP#166]
Why kotline use ":" for separation of input parameters and output in the declaration of functions and "->" in lambdas and type defenition? This interferes with the uniformity of the code. Lets add "->" as an alternative ":" in function declaration.

**Comment by gildor** [comment]
This is not a proper KEEP, please check README.
If just want to submit a feature request and do not want really work on KEEP (analyze backward compatibility, implementation details etc) just create an issue on Kotlin Issue tracker: kotl.in/issue

**Comment by Andru1999** [comment]
Ok, thenks a lot.
