### ISSUE TITLE
"and" type ,"or" type...

### ISSUE THREAD

**Issue by tianchaohongyu** [Kotlin/KEEP#167]
Such problems are often encountered in actual development.

A method requires processing Int, Double, String at the same time. At this time, it can only be that either three methods are used to deal with them separately, or the type is set to Any and the runtime exception is checked when the incoming error type is thrown.
Sequencing and serializing some data to hard disk requires that both Seriazable and Comparable be the type. There is no way to define any at this time, and then throw runtime exceptions when checking for incoming error types.
A method needs to deal with the digital Number class, but does not want to receive the Byte byte class. At present, there is no way but to define it as Number, and then check that the runtime exception is thrown when the Byte is passed in.
Expect 1.4 to introduce combination types to solve these problems.

"or" type, A | B, A or B, manifestation: direct operation can only be the intersecting part, their unique functions need to determine the specific type first.
The
"and" type, A&B, is both A class and B class. It can perform all functions of A and B directly.
"Exclusion" type, A-B, belongs to category A but does not allow category B (parent-child class, etc.). It shows that only all functions of A can be operated directly.

**Comment by udalov** [comment]
Hi @tianchaohongyu,

As per [§ How to propose](https://github.com/Kotlin/KEEP/blob/master/README.md#how-to-propose), if you only have a vague feature idea, please report in via [YouTrack](https://kotl.in/issue), [#language-proposals Slack channel](https://kotlinlang.slack.com/messages/language-proposals/), or [Forum's Language design category](https://discuss.kotlinlang.org/c/language-design). Thank you.
