### ISSUE TITLE
Overload resolution ambiguity. (duplicate name for fieldName and method with property access syntax)

### ISSUE THREAD

**Issue by zxj5470** [Kotlin/KEEP#180]
These's a third-party jar codes:
```java
public class ApiException extends Throwable {
	public String message;
}
```

And we all know `java.lang.Throwable` has `getMessage()` method.

And we call it in Kotlin:
```kotlin
val t = ApiException()
t.message //Overload resolution ambiguity.
```

Is there a solution like @FunctionCall or @FieldCall to specify ambiguity?

**Comment by gildor** [comment]
This is not a KEEP proposal (see [README](https://github.com/Kotlin/KEEP/blob/master/README.md), please [create an issue](https://kotl.in/issue) on Kotlin Issue tracker instead
