### ISSUE TITLE
Lambda-based pseudo-constructors for Map, by analogy with List

### ISSUE THREAD

**Issue by Spheniscine** [Kotlin/KEEP#183]
I think it would be useful for the standard library to include pseudo-constructors for [Map](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-map/index.html#kotlin.collections.Map) and [MutableMap](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-map/index.html#kotlin.collections.MutableMap), by analogy with the existing ones for [List](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-list.html) and [MutableList](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.collections/-mutable-list.html)

I propose that their signatures look something like these ones (source code given for example; feel free to improve if needed)
```
inline fun <K, V> Map(size: Int, init: (Int) -> Pair<K, V>) = mapOf(*Array(size) { init(it) })

inline fun <K, V> MutableMap(size: Int, init: (Int) -> Pair<K, V>) = mutableMapOf(*Array(size) { init(it) })

inline fun <K, V> Map(keys: Iterable<K>, init: (K) -> V): Map<K, V> = MutableMap(keys, init)

inline fun <K, V> MutableMap(keys: Iterable<K>, init: (K) -> V): MutableMap<K, V> {
    val r = mutableMapOf<K, V>()
    for (key in keys) {
        r[key] = init(key)
    }
    return r
}
```

The former two accept a size and initializes by a lambda generating key-value pairs. They're much like the List pseudo-constructors, except that the lambda needs to return a pair.

The latter two accept the keys as an Iterable (e.g. lists or ranges). The init lambda in this case accepts the key as the index.

**Rationale**
Just like the List pseudo-constructors, these allow you to initialize maps without manually defining an initialization loop. Additionally, these allow you to initialize a value as a Map instead of a MutableMap if you don't need to change it after initialization.

**Comment by fvasco** [comment]
I am not really convinced, `List` and `Map` are different.
`List` uses `index`es, `Map` not.

Starting by `Iterable` of keys looks more meaningful, but I consider the current library state adeguate

	val map=(1..10).map { it to it*it }.toMap()

My only proposal about this KEEP is something like

	val map=(1..10).toMap { it to it*it }

to halve the allocation.

**Comment by Spheniscine** [comment]
> I am not really convinced, `List` and `Map` are different.
> `List` uses `index`es, `Map` not.
> 
> Starting by `Iterable` of keys looks more meaningful, but I consider the current library state adeguate
> 
> ```
> val map=(1..10).map { it to it*it }.toMap()
> ```
> My only proposal about this KEEP is something like
> 
> ```
> val map=(1..10).toMap { it to it*it }
> ```
> to halve the allocation.

Yeah I just rediscovered that library extension Iterable<Pair<K, V>>.toMap(), which does do what I want with this proposal, but is somewhat less-than-computationally-optimal, as you noted.

**Comment by gildor** [comment]
there is a set of extensions `associate*` that solves this use case and it a bit more idiomatic:

For example
```
(1..10).map { it to it*it }
// or proposed extension
(1..10).toMap { it to it*it }
```

Can be directly rewirtten like this:
```
(1..10).associate { it to it * it }
```

Or more idiomatic version of this:
```
(1..10).associateWith { it * it }
```

There is no mutable map version, but as with many other similar extensions there a `associate*To` extensions, that allows you to pass any existing map including mutable one:
```
(1..10).associateWithTo(mutableMapOf()) { it * it }
```

**Comment by Fleshgrinder** [comment]
What I’d like to see would be actual builders for all collection types, so something along the following lines:

```kotlin
inline class MapBuilder<K, V>(private val map: MutableMap<K, V>) : MutableMap<K, V> {
    // ...
    infix fun K.to(key: V) = map.put(this, key)
    operator fun K.invoke(value: V) = map.put(this, value)
}

inline fun <K, V> buildMutableMap(builder: MapBuilder<K, V>.() -> Unit): MutableMap<K, V> {
    val map = mutableMapOf<K, V>()
    MapBuilder(map).apply(builder)
    return map
}

inline fun <K, V> buildMap(builder: MapBuilder<K, V>.() -> Unit): Map<K, V> =
    buildMutableMap(builder).toMap()

inline class ListBuilder<E>(private val list: MutableList<E>) : MutableList<E> {
    // ...
}

inline fun <E> buildMutableList(builder: ListBuilder<E>.() -> Unit): MutableList<E> {
    val list = mutableListOf<E>()
    ListBuilder(list).apply(builder)
    return list
}

inline fun <E> buildList(builder: ListBuilder<E>.() -> Unit): List<E> =
    buildMutableList(builder).toList()

fun main() {
    val m1 = mutableMapOf<String, String>().apply {
        this["foo"] = "bar"
        this["x"] = "y"
    }.toMap()

    val m2 = buildMap<String, String> {
        "foo" to "bar"
        "x" to "y"
    }

    val l1 = mutableListOf<String>().apply {
        add("foo")
        add("bar")
    }.toList()

    val l2 = buildList<String> {
        add("foo")
        add("bar")
    }
}
```

Especially the map case is much nicer.

**Comment by elizarov** [comment]
See https://youtrack.jetbrains.com/issue/KT-15363
