### ISSUE TITLE
Parcelize + inline class issue

### ISSUE THREAD

**Issue by AlexGianq** [Kotlin/KEEP#187]
Hi there !
When using a `@Parcelize` with an inline class, the actual `MyClass.Creator.createFromParcel()` will complain that the constructor is inaccessible to class `MyClass.Creator`.
Example :
```
    @Parcelize
    data class MyClass(val price: Price)


    inline class Price(val euros: Double)
```
I checked the byteCode and :
- the `private <init>(D)` is indeed not accessible
- the `public synthetic <init>(DILkotlin/jvm/internal/DefaultConstructorMarker;)` is accessible, but I guess this is not the one that Creator will use

If I turn my `Price` into a `data class`, then the `<init>(D)` becomes public and the runtime won't crash...

Thanks !

**Comment by fvasco** [comment]
Are you read the [project home page](https://github.com/Kotlin/KEEP#how-to-propose)?

**Comment by AlexGianq** [comment]
OK, sorry for that.
I'm closing the issue.
