### ISSUE TITLE
Hot reload

### ISSUE THREAD

**Issue by corporatepiyush** [Kotlin/KEEP#188]
Is it possible to automatically reload the kotlin scipt file at runtime when it changes without restarting JVM ?

**Comment by fvasco** [comment]
Are you read the [project home page](https://github.com/Kotlin/KEEP#how-to-propose)?

**Comment by corporatepiyush** [comment]
Yes. I also read the proposal for [scripting-support ](https://github.com/Kotlin/KEEP/blob/master/proposals/scripting-support.md)

**Comment by ilya-g** [comment]
Please use the issue #75 for the discussion of that proposal.
