### ISSUE TITLE
Use TaskProvider API in kapt plugin

### ISSUE THREAD

**Issue by remcomokveld** [Kotlin/KEEP#189]
In version 5.1 Gradle introduced the TaskProvider API to avoid the eager configuration of tasks in the configuration phase. In Android Gradle Plugin 3.4.0, usage of this API was fully implemented as discussed in [this](https://youtu.be/sQC9-Rj2yLI) talk at Google IO.

More info on this API can be found here https://docs.gradle.org/current/userguide/task_configuration_avoidance.html

I was just looking at our project which currently has 50 modules. It creates over 8361 tasks in the configuration phase. 6920 of these tasks are reported to be created by the AGP, and 410 by the kotlin-android plugin.

When I comment out the kotlin-kapt plugin, the amount of tasks instantiated by `com.android.library` are reduced to 14 when running `./gradlew help`.

It seems like this task configuration avoidance has a huge impact on the sync time of Android Studio and according to the docs it shouldn't be too hard to convert creating tasks to registering tasks which creates TaskProviders.

**Comment by JakeWharton** [comment]
Why is this an issue on the KEEP repo? Seems like you should file a bug on YouTrack.

**Comment by remcomokveld** [comment]
Yeah my bad, closing now
