### ISSUE TITLE
Allow 'break' & 'continue' in 'when'

### ISSUE THREAD

**Issue by dnpetrov** [Kotlin/KEEP#192]
It should have the same meaning as `break` or `continue` inside equivalent `if` - that is, break/continue from the innermost loop.

**Comment by DanySK** [comment]
In my opinion, this would promote bad code practices.

**Comment by CommanderTvis** [comment]
`when` is not `switch`, so it shouldn't inherit its flaws.

**Comment by elizarov** [comment]
I has been implemented in Kotlin 1.4 -> https://youtrack.jetbrains.com/issue/KT-33413
