### ISSUE TITLE
@Parcelize: CREATOR.createFromParcel(_reply) returns Object instead of T

### ISSUE THREAD

**Issue by yuriykulikov** [Kotlin/KEEP#196]
If data classes annotated with @Parcelize are used with AIDL, Code generated by AIDL fails to compile because the CREATOR is not properly parametrized.

`if ((0!=_reply.readInt())) {
_result = com.mypackagename.MyCustomObject.CREATOR.createFromParcel(_reply);
}`

_result type is MyCustomObject, but MyCustomObject.CREATOR.createFromParcel returns Object.

Demo project to reproduce this: https://github.com/f0restgump92/android_aidl_kotlin_parcelize

Duplicate issue in Kotlin Tracker: https://youtrack.jetbrains.com/issue/KT-25807

**Comment by fvasco** [comment]
> This repository holds proposals for the Kotlin Programming Language.

https://github.com/Kotlin/KEEP#keep---kotlin-evolution-and-enhancement-process

**Comment by yuriykulikov** [comment]
This is a proposal for proposals/extensions/android-parcelable.md. actually this can be considered a bug.

**Comment by JakeWharton** [comment]
And it's already filed as such in the appropriate place, YouTrack.

**Comment by yuriykulikov** [comment]
This is not an appropriate place for this. Closing the issue.
