### ISSUE TITLE
Proposal of `suspend property`

### ISSUE THREAD

**Issue by Him188** [Kotlin/KEEP#203]
Considering the case:
The shop has its items named ShopItem, which have prices.
The price should be queried from a website.
Currently, we can only do this:
```kotlin
class ShopItem {
   suspend fun getPrice(): Int = TODO()
}
```

But it will be better if `price` is a property.
```kotlin
class ShopItem{
    suspend val price: Int get() = TODO()
}
```

Proposal:
- `suspend val` cannot have backing field. (must be `get() = `)
- `suspend val`  is compiled as a suspend function like `suspend fun getXXX()`

**Comment by gildor** [comment]
It's not a proper KEEP, please check README.md

Also, this was proposed and discussed in this issue (also see linked issues with different use cases):
https://youtrack.jetbrains.com/issue/KT-15555

**Comment by Him188** [comment]
Alright, thank you anyway

**Comment by Him188** [comment]
Alright, thank you anyway
