### ISSUE TITLE
matrixOf()

### ISSUE THREAD

**Issue by rachitmishra** [Kotlin/KEEP#208]
#### Problem: 

We can declare a (mutable) multidimensional array as:

```
fun matrixOf(row: Int, column: Int): Array<IntArray> {
	return Array(row) { IntArray(column) }
}
```

How can we add this to the std library?

(Pardon me, if this isn't the right place for this question)

**Comment by udalov** [comment]
There are YouTrack issues which might be interesting for you:
https://youtrack.jetbrains.com/issue/KT-21670
https://youtrack.jetbrains.com/issue/KT-26577

The KEEP repository is not the best place for such feature requests. As ReadMe states, it's only for full proposals, or drafts which could be turned into proposals.
