### ISSUE TITLE
Cancellability API

### ISSUE THREAD

**Issue by qwwdfsad** [Kotlin/KEEP#214]
This issue is to discuss the proposal to introduce `suspendCancellableCoroutine` API to standard library.
API includes `CancellableContinuation` and `CancellationSource`interfaces and `AbstractCoroutineContextKey` as interoperability tool for 3rd-party libraries

Proposal text is [here](https://github.com/Kotlin/KEEP/blob/cancellable-continuation/proposals/stdlib/cancellation.md)

**Comment by fvasco** [comment]
What happen using `suspendCancellableCoroutine` on an already cancelled coroutine?
In the "Integration example", the `suspendCancellableCoroutine` lambda parameter will be invoked in this case?
`cancel` is invoked syncrhonous on cancelled coroutine?
If `await` is invoked on a completend future from a cancelled coroutine?
I think may be useful explain what should happen inverting `whenComplete` and `cont.invokeOnCancellation`.

`CancellationSource.attach` use a `CancellableContinuation`, so it is able to `resume` it. Is it expected? I fear this design can be abused.

> All new API will be added to new kotlin.coroutines.cancellation package

Are you considered to resume `kotlin.experimental.coroutines.cancellation` to provide a smother transition from the experimental API to a stable one?

> How to report double resume that typically is a programmer error

How this question is related to this issue?

**Comment by qwwdfsad** [comment]
>What happen using suspendCancellableCoroutine on an already cancelled coroutine?

Yes, the `block` will be invoked and `CancellationException` will be thrown.

> cancel is invoked syncrhonous on cancelled coroutine?

Could you please elaborate on what do you mean? Cancel can be invoked both synchronously and asynchronously.

>Is it expected? I fear this design can be abused.

Yes, it is expected; yes, it can be abused. An alternative solution would be to provide a one more super-interface (e.g. `Cancellable`) with a single method, implement it in `CancellableContinuation` and use it in `CancellationSource`.
But taking into account a pretty low-level design of `CancellationSource` (=> it won't be implemented directly in the typical applications), it would be overkill: bloated bytecode size, one more interface, one more IDE autocompletion noun (and `Cancellable` is a widespread term!)

>Are you considered to resume kotlin.experimental.coroutines.cancellation to provide a smother transition from the experimental API to a stable one?

No, `experimental` package was used **only** for experimental **language** feature. API will be marked with `@ExperimentalStdlibAPI` until at least Kotlin 1.5 instead.

>How this question is related to this issue?

`CancellableContinuation` is, by design, a concurrent entity. In concurrent environments, it's not a big-deal to have a double-resume bug. And the question here is to how to gracefully report that problem to the user.

**Comment by fvasco** [comment]
Hi, @qwwdfsad,
thank you for reply.
Maybe you should consider to integrate this point into the KEEP.

> Could you please elaborate on what do you mean?

Using a cancelled `CompletableFuture` on a cancelled coroutine, it is not clear for me what print this code:

```kotlin
suspend fun <T> CompletableFuture<T>.await(): T = suspendCancellableCoroutine { cont ->
      print(1)
      whenComplete { result, error ->
          print("resumeWithException")
          if (error != null) cont.resumeWithException(error)
          else cont.resume(result)
      }

      print(2)
      cont.invokeOnCancellation {
          print("cancel")
          cancel(/* mayInterruptIfRunning: */ false)
      }
      print(3)
}
```

So it is not clear if I can put `whenComplete` after `cont.invokeOnCancellation`.
I may suspect that this design choices are defined elsewhere, but there is no reference in this KEEP.

**Comment by qwwdfsad** [comment]
Thanks for your concerns, I'll describe these details in the documentation.

>So it is not clear if I can put whenComplete after cont.invokeOnCancellation

`whenComplete` and `invokeOnCancellation` are asynchronous by their nature, meaning that they can be invoked in any order. Thus, with a proper design, swapping these two should not change any observable behaviour.

**Comment by fvasco** [comment]
> `whenComplete` and `invokeOnCancellation` are asynchronous by their nature, meaning that they can be invoked in any order

You are right, but a completed `CompletableFuture` on an already cancelled coroutine is a special case.

I'll try to explain better, some possible outputs are:

```
1
resumeWithException
2
cancel
3
```

```
1
resumeWithException
2
3
cancel
```

```
1
resumeWithException
2
3
```

**Comment by qwwdfsad** [comment]
We decided not to implement it in the standard library, at least for now.

The proposal doesn't take into account prompt cancellation and also does introduce significant complexity due to the [`getResultOrMarkSuspended`](https://github.com/JetBrains/kotlin/commit/70389c75d077b59fcaff50f1e734c9bf4d6c6518) API.

The state of the polymorphic context elements is left out of the scope of this KEEP and its fate will be decided in Kotlin 1.7.0
