### ISSUE TITLE
Cannot import class from other kotlin script file

### ISSUE THREAD

**Issue by Wanther** [Kotlin/KEEP#218]
file1: `src/models.kts`
```kotlin
class ClassA(private val k: String, private val v: String)
```

file2: `src/test.main.kts`
```kotlin
@file:Import("models.kts")

val a = ClassA("key", "value")
```

I tried in console:
```bash
kotlinc -cp $KOTLIN_HOME/lib/kotlin-main-kts.jar -script src/test.main.kts
kotlin -cp $KOTLIN_HOME/lib/kotlin-main-kts.jar src/test.main.kts
kotlin src/test.main.kts
```

every command failed with messages:

```
error: unresolved reference: ClassA (test.main.kts:3:9)
src/test.main.kts:3:9: error: unresolved reference: ClassA
val a = ClassA("key", "value")
```
Doc says:

https://github.com/Kotlin/KEEP/blob/master/proposals/scripting-support.md

@Import allows importing another script into a given one. All the actions specified in the imported script run before all the actions specified in the given script and all the properties, functions and classes defined in the imported scripts become visible for the given script.

"classes defined in the imported scripts become visible for the given script", how do I correct my code?

**Comment by ligee** [comment]
Sorry for the long silence, seems we have some gaps in processing issues from here.
Anyway, this is probably the wrong place to ask for support about Kotlin functionality, this repo is intended for the Kotlin evolution proposals and discussions. Please you Kotlin YouTrack or Kotlin Slack for it.

About the issue - the importing feature is very experimental, so do not expect flawless functionality there. 
I can imagine two possible things to try: first, use the same extension for the imported script, and second - use the same root for the imported script, so something like `@file:import("src/models.main.kts")` (provided that you'll rename the models file accordingly) will hopefully work.

You can also have look at the working examples at https://github.com/Kotlin/kotlin-script-examples

If you have further problems or questions, please use YouTrack or Slack.
