### ISSUE TITLE
Android Navigation Safe-Args plugin generates code that is incompatible with strict mode

### ISSUE THREAD

**Issue by Computr0n** [Kotlin/KEEP#219]
```kotlin

class InAppPairFragmentDirections private constructor() {
  private data class ActionToDeviceInformation(
    val type: Int = 1
  ) : NavDirections {
    override fun getActionId(): Int = R.id.action_to_device_information

    override fun getArguments(): Bundle {
      val result = Bundle()
      result.putInt("type", this.type)
      return result
    }
  }

  companion object {
    fun actionToDeviceInformation(type: Int = 1): NavDirections = ActionToDeviceInformation(type)
  }
}

```

that is example code that is genned by the [Android Navigation SafeArgs plugin](https://developer.android.com/jetpack/androidx/releases/navigation#safe_args) and when i put my library in strict mode I can't opt it out of erroring.

What is the solution for this issue?

**Comment by JakeWharton** [comment]
File a bug at https://issuetracker.google.com/issues/new?component=409828. This has nothing to do with Kotlin or its enhancement process.

**Comment by Computr0n** [comment]
thanks for the link. just filed.
