### ISSUE TITLE
lateinit val

### ISSUE THREAD

**Issue by AkashaP** [Kotlin/KEEP#224]
There are quite a few hits on Google about a 'lateinit val', which specifically behaves like _lateinit var_, but can only be set once like val. Use case are for example declaring fields whos values are calculated in a constructor or other method, but should not be modifiable by the public API, with minimal but clear syntax. It could be used like this:

```
public class Something(val data:Int) {
	lateinit val data2:String
	
	fun calculateData() {
		// Perhaps some expensive or blocking operation that shouldn't be put into the constructor
		data2 = (data * data).toString()
	}
}
```

The lateinit val can be a lateinit var but it's publicly modifiable, which may be undesirable.

there is a thread on StackOverflow that describes multiple ways of implementing this using intermediate language features
https://stackoverflow.com/questions/48443167/kotlin-lateinit-to-val-or-alternatively-a-var-that-can-set-once

This could be supported first class by the language, however. Without any intermediate language features, the only way I can think of doing this is to use a getter-only val backed by a mutable private field like this. 
```
public class Something() {
	private lateinit var _readOnlyThing:String
	public val readOnlyThing:String
		get() = _readOnlyThing // or a java-like getter function
	        // no setter

	fun calculateData() {
		// Perhaps some expensive or blocking operation that shouldn't be put into the constructor
		_readOnlyThing = "1"
	}
}
```

It would be nice to be able to do this in one line and one variable though. My memory is hazy but over in C# I believe I used to be able to do it via visibility modifiers on the getters and setters, which fulfills the use case relatively concisely:
```
public class SomethingInCSharp {
	public string ReadonlyThing { public get; private set; }
	void calculateData() {
		// Perhaps some expensive or blocking operation that shouldn't be put into the constructor
		ReadOnlyThing = "1"
	}
}
```

**Comment by AkashaP** [comment]
of course, checking the documentation i found that kotlin setters can also have visibility modifiers, which means i can probably already emulate the syntax concisely enough like this
```
	lateinit var setterVisibility: String
		private set // the setter is private and has the default implementation
```
didn't realise before

**Comment by fvasco** [comment]
Please consider to read the [repository guidelines](https://github.com/Kotlin/KEEP/blob/master/README.md) and to use a [forum](https://discuss.kotlinlang.org/) to start a discussion.

**Comment by alekseytomin** [comment]
It seems to me that it is better to use `val readOnlyThing:String by lazy { ... }`

**Comment by oh-Rin** [comment]
> It seems to me that it is better to use `val readOnlyThing:String by lazy { ... }`

But you know, sometimes what we want to initialize may be dynamic, `by lazy { ... }` means it has no way to know the external parameters

**Comment by alekseytomin** [comment]
> But you know, sometimes what we want to initialize may be dynamic, `by lazy { ... }` means it has no way to know the external parameters

```
private val storedExternalParameter = ...
val readOnlyThing:String by lazy { ... }
```

**Comment by oh-Rin** [comment]
> ```
> private val storedExternalParameter = ...
> val readOnlyThing:String by lazy { ... }
> ```

Yeah sure, but I think `lateinit val` will be cleaner

**Comment by alekseytomin** [comment]
> > ```
> > private val storedExternalParameter = ...
> > val readOnlyThing:String by lazy { ... }
> > ```
> 
> Yeah sure, but I think `lateinit val` will be cleaner

I was using `lateinit var` and had a lot of errors with it.
Now I've replaced it all with `lazy` and the code works fine.
`lateinit` can't be used without **!!** checks and we have `null pointer exception` back.

**Comment by oh-Rin** [comment]
> I was using `lateinit var` and had a lot of errors with it.
> Now I've replaced it all with `lazy` and the code works fine.
> `lateinit` can't be used without **!!** checks and we have `null pointer exception` back.

In fact, you are right. But too much `!!` or `?` will affect the cleanliness of the code, and they are very annoying. So when we can fully understand whether the properties are initialized, the code world without `!!` and `?` will be better

**Comment by alekseytomin** [comment]
> Because many times we don’t actually need to worry about `NPE`, so when we can fully understand whether the properties are initialized, the code world without `!!` and `?` will be better

With `lateinit` we can NOT understand anything. Precisely speaking in the future our understanding will be false.

**Comment by elizarov** [comment]
I'm closing this issue in favor of keeping track for `lateinit val` feature request and the corresponding discussion in this issue: https://youtrack.jetbrains.com/issue/KT-28413. Please, vote there 👍
