### ISSUE TITLE
Parcelize annotation problem

### ISSUE THREAD

**Issue by hotsx** [Kotlin/KEEP#231]
Forgive my poor english....

When i use plugins "kotlin-parcelize" 

There is a problem in this situation:

`@Parcelize
data class Medium<T : Parcelable>(val data: List<T>) : Parcelable`

Error : Cannot reference non-static type variable T from static context

but on "1.4.10" "kotlin-android-extensions" has no error.

**Comment by altavir** [comment]
What does it have to do with language evolution? Please use the issue tracker instead.

**Comment by hotsx** [comment]
> What does it have to do with language evolution? Please use the issue tracker instead.

Thanks for reminding
