### ISSUE TITLE
Introduce an operator for unwrapping nullable values within an expression

### ISSUE THREAD

**Issue by pashko** [Kotlin/KEEP#245]
## Proposal

Introduce an operator that would allow to unwrap any number of nullable values within an expression and evaluate the whole expression to null if any of them are null

## Rationale

Using a nullable value where a non-nullable value is expected comes with some overhead. The overhead is much smaller if the variable is used as a receiver, but increases if it is passed to a function as a parameter:

```Kotlin
fun Foo.doStuff(): Foo {}
fun doStuffWith(foo: Foo): Foo {}

// non-nullable
val foo: Foo
foo.doStuff()
doStuffWith(foo)

// nullable
val foo: Foo?
foo?.doStuff() // quick and easy
foo?.let { doStuffWith(it) } // not so quick and easy
```
This becomes even more of an issue if there are several values that need to be unwrapped:
```Kotlin
fun doStuffWith(foo: Foo, bar: Bar, baz: Baz)

val foo: Foo?; val bar: Bar?; val baz: Baz?

foo?.let { foo ->
    bar?.let { bar ->
        baz?.let { baz ->
            doStuffWith(foo, bar, baz)
        }
    }
} // bad

if (foo != null && bar != null && baz != null) {
    doStuffWith(foo, bar, baz)
} // not too bad but doesn't work in some cases, like mutable fields or public properties declared in a different module

doStuffWith(foo ?: return, bar ?: return, baz ?: return) // neat but even more limited use cases
```
If Kotlin's `?` operator could unwrap a nullable value if it's not null, or evaluate the whole expression to null if it is null, this could be done as follows:
```Kotlin
val result = doStuffWith(foo?, bar?, baz?)
// ...is equivalent to
val foo1 = foo
val bar1 = bar
val baz1 = baz
val result = if (foo1 != null && bar1 != null && baz1 != null) {
    doStuffWith(foo1, bar1, baz1)
} else {
    null
}
```

## Other considerations

If Kotlin had such operator, it would change the semantics of `?.` from being a single "safe call" operator to two operators - first unwrap, then apply the regular `.` operator). This might make the following code ambiguous:
```Kotlin
fun doStuffWith(foo: Foo?): Foo {}
doStuffWith(foo?.value) // ambiguous, may be interpreted as foo?.let { doStuffWith(it.value) }
```

As an option, `??` operator which is used in some other languages for null coalescing (`?:` in Kotlin) could be used instead of a single question mark. In this case usage like `foo??.value` may need to be disallowed to avoid ambiguity.

Having such operator would mean that nullable functional values could be used simply as `lambda?(parameter)` (or `lambda??(parameter)`, instead of the current `lambda?.invoke(parameter)`.

**Comment by elizarov** [comment]
According to the contribution guidelines (see https://github.com/Kotlin/KEEP#contributing-use-cases-and-specific-enhancement-proposals) I've moved your proposal to your YT issue -> https://youtrack.jetbrains.com/issue/KT-45862
