### ISSUE TITLE
Wrong example code in "Built-in primitive value classes"

### ISSUE THREAD

**Issue by UgljesaPupavac** [Kotlin/KEEP#266]
Reading through [this chappter](https://github.com/Kotlin/KEEP/blob/master/notes/value-classes.md#built-in-primitive-value-classes) the example code suggests: 
```
fun main() {
    val a = 2021
    val b = a
    println(a == b) // true -- same value
    println((a as Any) === (b as Any)) // false -- different instance
}
```
But last line  ```println((a as Any) === (b as Any)) // false -- different instance``` actually is wrong. This will print value of `true`. Even the playground is showing that.

**Comment by elizarov** [comment]
Thanks. Good catch!
