### ISSUE TITLE
Script Definition Template

### ISSUE THREAD

**Issue by ligee** [Kotlin/KEEP#28]
[initial proposal for Script Definition Template](https://github.com/Kotlin/KEEP/commit/bc7c86d54183d1decbb24a9ec41fa03ed2871118)

*_Open issues *_
- [ ] Controlling access to host app's APIs

**Comment by bsideup** [comment]
Alternatively, Kotlin might use `@file:org.jetbrains.kotlin.gradle.GradleScript()` notation.

Pros:
- Less typing and visual noise
- Parameterization with: `@file:foo.bar.MyScript(version=1.1)`

Cons:
- Instead of one, generic annotation, we have multiple of them - harder to find one in the compiler
- "Can I define multiple script annotations on the same file?"-like questions

**Comment by bsideup** [comment]
Just to note - there should be a way to mark script as Serializable (Spark-like use cases)

**Comment by bsideup** [comment]
Dependency resolver should be able to resolve other scripts as dependencies:

```
@file:include("./shared/code.kts")
```

**Comment by abreslav** [comment]
> Alternatively, Kotlin might use `@file:org.jetbrains.kotlin.gradle.GradleScript()` notation.

@bsideup this is only possible if `GradleScript` is an annotation class, and that prohibits many things, e.g. extending other classes.

**Comment by orangy** [comment]
`file:include` is good catch, but shouldn't be called `include` I think, because it's not actually textual inclusion.

**Comment by bsideup** [comment]
Naming is not my strongest skill :)

**Comment by ligee** [comment]
@bsideup: about serialization: do you see any problem in simply marking script template class as Serializable? It will be actually the base class for the generated script class.

**Comment by elifarley** [comment]
> file:include is good catch, but shouldn't be called include I think, because it's not actually textual inclusion.

Maybe
`@file:import("./shared/code.kts")`
(or `importscript`)

**Comment by Jire** [comment]
What about support for calling scripts and their functions from regular Kotlin code? And the other way around; what about scripts using regular Kotlin code?

**Comment by abreslav** [comment]
@Jire 

> What about support for calling scripts and their functions from regular Kotlin code?

Script is compiled to a class that can be used by other code.

> And the other way around; what about scripts using regular Kotlin code?

Of course, scripts can use other code

**Comment by Jire** [comment]
@abreslav Wow perfect!! Very excited to see this in action.

**Comment by jonninja** [comment]
If scripts can call other code (a good thing), will there be a way to limit which packages can be imported? This would allow us to prevent authors from writing code that we'd prefer to limit.

**Comment by cypressious** [comment]
You have `internal` for that.

**Comment by abreslav** [comment]
> If scripts can call other code (a good thing), will there be a way to limit which packages can be imported? This would allow us to prevent authors from writing code that we'd prefer to limit.

I don't see why this needs to be limited to scripts only. Seconding @cypressious on this: visibility modifiers can be used.

**Comment by Cypher121** [comment]
I fail to see how `internal` and other modifiers cover that question. It's more about restricting what functionality can script invoke: for example, if I'm using scripts for some sort of plugin system and don't want to run them as full-privilege code, there's no way to restrict them from accessing system, fs, net or other sensitive classes by using visibility, unless it's somehow possible to decrease it for that specific script without altering the original code.

Although there may be one with security managers, but that's still worth looking into.

**Comment by ryleykimmel** [comment]
When dealing with scripts will there be or is there currently a type (or other identifier) that represents a Kotlin script vs a Kotlin class or must we assume that the file extension ".kts" is a script?

**Comment by abreslav** [comment]
@ryleykimmel Yes, there will be a way to see if a class or instance represents a script.

**Comment by ryleykimmel** [comment]
@abreslav Is it present in the 1.1 preview?

**Comment by abreslav** [comment]
Can't check quickly ATM. CC @ligee

**Comment by jonninja** [comment]
@abreslav It _is_ different from internal. As @Cypher121 describes, this is about limiting what a script writer has access to. We have a tool that we provide that is currently configured with XML. The XML is a mess, and it would be really beautiful to allow the configuration as a kotlin script. However, I don't want configuration writers to do all kinds of things... I want to limit the library functionality so they don't do dangerous things. 

I guess a most basic implementation would be an attribute of ScriptDefinitionTemplate that defined the allowed packages as a regex or other patterns. Another option would be to have an attribute that, if true, didn't allow for importing... that is, only 'ScriptImplicitImports' would be allowed. This might solve the problem just as well.

**Comment by abreslav** [comment]
> this is about limiting what a script writer has access to

@jonninja The important part of your request is that compile-time safety will likely not be good enough for it: if the script puts a bunch of bytes together and loads them as a class that actually accesses bad APIs, no static checks in Kotlin will mitigate that. So, the runtime-support is required, and there we have mostly ClassLoaders and SecurityManager.

Whether we should do something in the script templates to facilitate such configuration, or just rely on what JRE and JSR 223 provide, is a good question. // CC @ligee

**Comment by jonninja** [comment]
That makes sense. Certainly from the use cases I'm considering, this isn't much of an issue, as the access limitations are used to guide script writers. I just want a way to make clear what is supported functionality.

**Comment by ligee** [comment]
@ryleykimmel the proper reflection for script classes is not yet part of 1.1, and even not fully designed yet. See https://youtrack.jetbrains.com/issue/KT-13382

**Comment by ligee** [comment]
@jonninja you may (to the certain extent) control the runtime security using SecurityManager, since script execution is at your hands. You may also control script's classpath with DependenciesResolver.
Deeper restrictions will need to be thought through carefully, because even limiting imports is sort of language level change. And then logically the next requirement would be to define which language constructs are allowed in a particular script, like with groovy's SecureASTCustomizer. Which looks scary for me. :)
But we'll keep that in mind, thank you for the suggestion.

**Comment by abreslav** [comment]
@ligee I think SecureASTCustomizer is far from what we are looking for here. Controlling access to APIs is very relevant when Kotlin is used for customization/scripting inside a bigger app

**Comment by DaanDeMeyer** [comment]
Could the @file:ScriptTemplate annotation be extended to allow pointing to an url from which an IDE could download the script template?

Along with support in Intellij for editing single script files without creating a project, this would provide users with an intuitive way of using Intellij as a script editor without having to download separate script definitions or deal with lots of project files.

**Comment by abreslav** [comment]
@DaanDeMeyer Interesting use case. @ligee What do you think?

**Comment by Cypher121** [comment]
Since template is just a kt/class file, wouldn't pointing to remote URL be a security problem?

**Comment by ilya-g** [comment]
Is this proposal somehow related to the recently introduced `kotlin.script.StandardScriptTemplate` in kotlin-runtime?

**Comment by voddan** [comment]
Do other languages have such a mechanism? What would be the closes analogs?

**Comment by raniejade** [comment]
Are there any plans for scripts to have an output? (return something)

**Comment by cypressious** [comment]
You can print to stdout or stderr or exit with a non-zero exit code.

Am 03.12.2016 08:40 schrieb "Ranie Jade Ramiso" <notifications@github.com>:

Are there any plans for scripts to have an output? (return something)

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/Kotlin/KEEP/issues/28#issuecomment-264623771>, or mute
the thread

**Comment by mkobit** [comment]
> Could the @file:ScriptTemplate annotation be extended to allow pointing to an url from which an IDE could download the script template?

I really like the idea of this. It seems like it would be useful to be able to have some notion of script template resolution without having to download additional plugins, pull down and activate something (like how [GDSL](https://confluence.jetbrains.com/display/GRVY/Scripting+IDE+for+DSL+awareness)), or having to configure IntelliJ to properly understand those files.

The way I generally (and others at my work) use IntelliJ is for importing Gradle projects and letting IntelliJ figure out all the modules and do all the dependency resolution magic. We use Jenkins 2.0 and the Jenkins pipeline functionality which requires a `Jenkinsfile` Groovy script in the base of the process. It is difficult for others to develop against the `Jenkinsfile` because of the complexities and not having code documentation. Jenkins vends a GDSL but the workflow is confusing and too many steps for a lot of the developers at my work.

The idea that a script template can simply be pointed to a url and get a lot of the development features seems like it would be useful.

**Comment by dzharkov** [comment]
Closed in favor of #75
