### ISSUE TITLE
Generic providedProperties do not seem to work

### ISSUE THREAD

**Issue by devgg** [Kotlin/KEEP#287]
Providing a generic type in providedProperties does not seem to work:

ScriptCompilationConfiguration:
```
providedProperties(
  "test1" to
    Map::class.createType(
      arguments =
        listOf(
          KTypeProjection.invariant(String::class.createType()),
          KTypeProjection.invariant(String::class.createType())
        )
    )
)
```

ScriptEvaluationConfiguration:
```providedProperties("test1" to mapOf("test2" to "output")) ```

Script:
```test1["test2"]```

I am getting 
`[ERROR] Type inference failed. The value of the type parameter K should be mentioned in input types (argument types, receiver type or expected type). Try to specify it explicitly.`

**Comment by fvasco** [comment]
_This repository contains proposals for the Kotlin Programming Language, including draft design notes and discussions for in-progress proposals as well as the design documentation on the changes that were already implemented._

You should refer to https://kotlinlang.org/community/
