### ISSUE TITLE
Easier custom iterables with cleanup support

### ISSUE THREAD

**Issue by soywiz** [Kotlin/KEEP#323]
Creating custom iterators usually requires an iterartor object, and also doesn't have the concept of freeing once done. Because of that `Flow.collect { }` is required and cannot be used with a plain `for`. This approach would allow to make some classes iterable potentially without allocatingand with the ability of executing code after the loop has been completed in an easy way.

Based on `opApply` from the D programming language:
https://tour.dlang.org/tour/en/gems/opdispatch-opapply#/opApply:~:text=ABC%22)%3B-,opApply,-An%20alternative%20way

In the case of Kotlin I would propose introduce a new operator function, for example `operator fun each`:

### `each` definition

```kotlin
inline class MyCustomObject(val count: Int)

/**
 * returned value from the block callback is interpreted as:
 * - true -> should continue the iteration if not in the end
 * - false -> should break the iteration and cleanup
 */
inline operator fun MyCustomObject.each(block: (value: Int) -> Boolean) {
    try {
        for (n in 0 until this.count) {
            if (!block(it)) break
        }
    } finally{
        free()
    }
}
```

### How to use

```kotlin
  for (n in MyCustomObject(10)) {
     if (n == 2) continue // returns the block() callback with true to continue the iteration
     if (n == 5) break // returns the block() callback with false to stop the iteration
     println(n)
     // implicitly returns the block() callback with true to continue the iteration
  }
```

### Transformed into:

```kotlin
  // transformed into:
  MyCustomObject(10).each {
     if (n == 2) return@each true
     if (n == 5) return@each false
     println(n)
     true
  }

```

**Comment by elizarov** [comment]
Please, see [KT-33851](https://youtrack.jetbrains.com/issue/KT-33851) iterator-less for-statement operator convention for push-based data streams. It seems to be exactly the issue you are looking for.
