### ISSUE TITLE
Kotlin Usigned Operations

### ISSUE THREAD

**Issue by Pseudow** [Kotlin/KEEP#359]
Could we please add some kind of operations between Unsigned types like for example this:
```kotlin
val uShort1: UShort = 1u
val uShort2: UShort = 1u

val uShort3: UShort = uShort1 + uShort2
```

**Comment by quickstep24** [comment]
The operations are there, but they implicitly cast to `UInt`.
Operator `plus` is declared
```
@kotlin.internal.InlineOnly public final inline operator fun plus(other: kotlin.UShort): kotlin.UInt
```
So you have to write
```
val uShort3: UShort = (uShort1 + uShort2).toUShort()
```

**Comment by r4zzz4k** [comment]
Also, this repository is not meant for general feature requests. As stated in README, it describes design notes of language changes which are already being coordinated with Kotlin language designers. To share your feature requests or bug reports, please consider using [YouTrack](https://youtrack.jetbrains.com/issues/KT).

**Comment by nikitabobko** [comment]
@r4zzz4k is completely right here. Please use YouTrack for feature requests or bug reports
