### ISSUE TITLE
Request: offer some way that the language could enforce uniqueness of constants inside a class/interface

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Kotlin/KEEP#360]
I was told to request this from here:
https://youtrack.jetbrains.com/issue/IDEA-330407

Basically I want some classes (or class-like) to have constants that will not be duplicates, to prevent colliding of behaviors related to them.
For example for Analytics, to report of a specific event, I don't want someone else to create a constant that has the same value as this event yet for a different one.

**Comment by nikitabobko** [comment]
Sorry that I have to forward you once again, but KEEP is for well-formed finished design proposals and design notes with motivation, use cases, feature interaction analysis, etc.

For not well-formed user requests we still use the YouTrack.

I extracted your request to KT YouTrack issue: https://youtrack.jetbrains.com/issue/KT-61468

**Comment by AndroidDeveloperLB** [comment]
Odd because that's where it started from...
