### ISSUE TITLE
Delegated Methods

### ISSUE THREAD

**Issue by debdattabasu** [Kotlin/KEEP#48]
Hi. 
We are using Kotlin for implementing realtime game servers, and we use java dynamic proxies heavily. Delegated properties in Kotlin are awesome. I would love to see a feature for delegated methods, which would allow us to implement something similar to java dynamic proxies in a statically typed way. Consider the use case: 

```
interface RemoteService {

    fun doSomethingSwesome(param: String) : String by RemoteInvocationHandler()
}

class RemoteInvocationHandler {
    fun invoke(obj: Any, method: KCallable, params: Array<Any>) {
        //forward invocation to remote service and return result
    }
}


```

Would love to hear your thoughts on this

**Comment by yole** [comment]
As the README says, issues in the KEEP repository should be used for discussing existing KEEPs. If you'd like to suggest a feature in Kotlin, please use the #language-proposals channel in the Kotlin Slack, the "Language design" category in the forum or file an issue in YouTrack.
