### ISSUE TITLE
Read-only and mutable abstract collections

### ISSUE THREAD

**Issue by ilya-g** [Kotlin/KEEP#53]
Discussions about the [Read-only and mutable abstract collections](../blob/master/proposals/stdlib/abstract-collections.md) will be held here.

**Comment by damianw** [comment]
Since Kotlin has default interface implementations, would it be better (or possible) to implement any of these as interfaces instead of abstract classes?

**Comment by ilya-g** [comment]
@damianw Interfaces cannot have state, cannot implement members of `Any` (namely `hashCode`, `equals` and `toString`). Also when two unrelated interfaces declare the same member it burdens an implementor of them both to have an override to select which one to use.

Making abstract mutable collections become interfaces would render impossible to reuse JDK implementations.
