### ISSUE TITLE
Underscore for unused parameters

### ISSUE THREAD

**Issue by dzharkov** [Kotlin/KEEP#55]
See https://github.com/Kotlin/KEEP/blob/master/proposals/underscore-for-unused-parameters.md

**Comment by scf4** [comment]
Hey @dzharkov, any movement on this proposal?

**Comment by gildor** [comment]
@scf4 [released in Kotlin 1.1](https://kotlinlang.org/docs/reference/whatsnew11.html#underscores-for-unused-parameters)

**Comment by dzharkov** [comment]
The declarations have been released in Kotlin 1.1, thus I'm closing the KEEP. Do not hesitate to open a [YouTrack issue](https://kotl.in/issue) for any additional suggestions.
