### ISSUE TITLE
Underscores in numeric literals

### ISSUE THREAD

**Issue by yole** [Kotlin/KEEP#59]
Discussion of [Underscores in numeric literals](https://github.com/Kotlin/KEEP/blob/master/proposals/underscores-in-numeric-literals.md) KEEP.

**Comment by voddan** [comment]
Shouldn't implemented proposals be closed?

**Comment by dzharkov** [comment]
The feature has been released in Kotlin 1.1, thus I'm closing the KEEP. Do not hesitate to open a [YouTrack issue](https://kotl.in/issue) for any additional suggestions.
