### ISSUE TITLE
Generic values() and valueOf() for enums

### ISSUE THREAD

**Issue by yole** [Kotlin/KEEP#61]
Discussion of https://github.com/Kotlin/KEEP/blob/master/proposals/generic-values-and-valueof-for-enums.md

**Comment by elizarov** [comment]
I really need the same feature for non-reified generics, e.g. via reflection, when I only have KClass<E>, see https://youtrack.jetbrains.com/issue/KT-14743

**Comment by dzharkov** [comment]
The feature has been released in Kotlin 1.1, thus I'm closing the KEEP. Do not hesitate to open a [YouTrack issue](https://kotl.in/issue) for any additional suggestions.
