### ISSUE TITLE
Swift-style enums

### ISSUE THREAD

**Issue by Supuhstar** [Kotlin/KEEP#63]
[Swift has](https://developer.apple.com/library/content/documentation/Swift/Conceptual/Swift_Programming_Language/Enumerations.html) the [most powerful](https://appventure.me/2015/10/17/advanced-practical-enum-examples/) enum system I've ever seen. This stems from the ability to provide an enumerated value with a tuple, not at declaration, but at usage sites.

For instance, in the form of an SSCnCE:

```
// In Swift:

enum Intersection {
    case none
    case touching(point: CGPoint, touchesStart: Bool)
    case crossing(point: CGPoint)
}

class Line {
    // Some other vars and funcs like _rawIntersection declared here

    func intersection(with other: Line) -> Intersection {
        if let intersectionPoint = _rawIntersection(with: other) {
            if intersectionPoint == self.startingPoint
                || intersectionPoint == self.endPoint {
                return .touching(point: intersectionPoint, touchesStart: intersectionPoint == self.startingPoint)
            } else {
                return .crossing(point: intersectionPoint)
            }
        } else {
            return .none
        }
    }
}


let intersection = someLine.intersection(with: someOtherLine)
switch intersection {
    case .none: // the .none case has no associated value
        print("So far away...")

    case .touching(_): // Underscore ignores the value
        print("I'm touching you!")

    case .crossing(let point): // let saves the value
        print("Cross my", point, "and hope to die")
}
```

I don't even know how you'd do this in Kotlin. Maybe with optionals or subclasses or something. But that'd much more cumbersome and much less elegant.

Being able to have all the information you need right there when you need it, with only declaring the enum type and no helper classes or anything, is a very powerful thing. I've designed a datetime formatter, an automatic integer memory management system, a categorized searchable collection, and many other things with a Swift enum as the backend. This would be **awesome** to have in Kotlin!

**Comment by udalov** [comment]
Thanks for the report, but please note the following suggestion in the [ReadMe](https://github.com/Kotlin/KEEP/blob/master/README.md) in this repository:

> If you only have a vague feature idea, please share it in the [#language-proposals](https://kotlinlang.slack.com/messages/language-proposals/) channel in our public Slack (get invite [here](http://kotlinslackin.herokuapp.com/)), or in the [Forum's Language design category](https://discuss.kotlinlang.org/c/language-design).

We'd like the KEEP repository to contain structured, detailed and well formulated language feature proposals, so that we could handle the feedback and keep discussions productive and on point. Until you have the proposal, please discuss your idea in the Slack channel, the forum, or [YouTrack](http://kotl.in/issue). Thanks!

**Comment by Supuhstar** [comment]
Oops, sorry! I should've read the full readme first 🙇
