### ISSUE TITLE
Constant inlining

### ISSUE THREAD

**Issue by mfulton26** [Kotlin/KEEP#64]
I don't see a KEEP for [constant inlining](https://kotlinlang.org/docs/reference/whatsnew11.html#constant-inlining) so maybe there is a better place to ask this question but will this cause problems for large constant values or are `String` compile-time constants excluded from inlining? e.g. `const val PI_TO_1000_DIGITS = "3.14159..."`

**Comment by cypressious** [comment]
The [Slack](http://kotlinlang.slack.com/) or [Youtrack](https://youtrack.jetbrains.com/issues/KT) are probably better places to ask.

**Comment by udalov** [comment]
Indeed, please ask this in the Slack or file an issue in YouTrack. There's no KEEP because constant inlining is neither a language feature nor a library improvement. We're currently using the KEEP repository for feature proposals only.
