### ISSUE TITLE
apply label to control flow

### ISSUE THREAD

**Issue by lyrachord** [Kotlin/KEEP#67]
In java we can write the following code:
```java
//avoid more conditional variable
label: {
       main: while(offset<limit){
            if (doSomething()==ERROR) break label;
            while(true){
                   if(some()) continue main;
             }
       }
      Log("EOF");
      return;
}
completeSomething();
```

but till kotlin 1.1, label only for single loop. so you must write a single loop to wrapper like this
```kotlin
    //wrapper oneshot loop, just for additional control flow structure
    loop@ for (oneshot in 1..1) {
        for (i in 1..10) {
            println(i)
            if (i == 8) break@loop
        }
        println("next line")
    }
    println("loop@")

```
wait, As you known, label is applied to lambda, label@{}, the following from kotlin reference
```kotlin
fun foo() {
    ints.forEach lit@ {
        if (it == 0) return@lit
        print(it)
    }
}

```

So label@{} form can be applied loop.
```kotlin
    loop@ {
        for (i in 1..10) {
            println(i)
            if (i == 8) break@loop
        }
        println("next line")
    }
    println("loop@")

```
And label if and when is OK as well?

**Comment by yole** [comment]
KEEP issues are intended to be used for discussing specific KEEP proposals. If you want to make a suggestion for adding a feature to Kotlin and aren't ready to write a complete design proposal, please file a YouTrack issue.
