### ISSUE TITLE
Const reference-type function/lambda parameters.

### ISSUE THREAD

**Issue by nimtiazm** [Kotlin/KEEP#69]
A Function/lambda should be able to take a `const` parameter which is read-only. This will enable certain optimizations and will remove the need to copy references.

This feature will also enable a lot of gains when value-types are actually implemented in Kotlin but, they're not dependent on the availability of value-types in the language. But it's arguable if this feature depends on the availability of `const val` reference types (heap object that cannot be changed).

Keyword: Kotlin's `const` keyword can be used so there's no need to add a new one. 

The strawman syntax should make it look like the following:

```fun foo(const bar: Bar)...```

**Comment by yole** [comment]
KEEP issues are intended to be used for discussing specific KEEP proposals. If you want to make a suggestion for adding a feature to Kotlin and aren't ready to write a complete design proposal, please file a YouTrack issue.

**Comment by ilya-g** [comment]
What does this "read-only" means? What particular restrictions it imposes on `bar` parameter?

**Comment by nimtiazm** [comment]
`bar` param should be immutable/read-only.

**Comment by yole** [comment]
Let's not discuss this here, please.
