### ISSUE TITLE
Kotlin.system should use consistent naming for time measurement methods

### ISSUE THREAD

**Issue by mutexkid** [Kotlin/KEEP#74]
within `kotlin.system` there are the following methods: 
`fun measureNanoTime(block: () -> Unit): Long`
`fun measureTimeMillis(block: () -> Unit): Long`

in `measureNanoTime`, the unit of time, `nanoseconds` is mentioned before `Time`, while
in `measureTimeMillis`, the unit of time, `milliseconds` is mentioned after `Time`. 

Make the naming consistent here, by favoring either one or the other scheme. Suggest: 
`measureTimeNanos`
`measureTimeMillis`

**Comment by ilya-g** [comment]
The naming here reflects the naming of the JDK functions used to measure time: 
`System.currentTimeMillis()` and `System.nanoTime()`. 
AFAIK they are fundamentally different time sources and their difference lies not only in the time units. See the questions for some detail:
https://stackoverflow.com/questions/18513767/java-system-nanotime-vs-system-currenttimemillis-why-do-they-have-different
https://stackoverflow.com/questions/19052316/why-is-system-nanotime-way-slower-in-performance-than-system-currenttimemill
https://stackoverflow.com/questions/351565/system-currenttimemillis-vs-system-nanotime

**Comment by JakeWharton** [comment]
This should be closed as it's not a KEEP. At best it's a YouTrack issue.

**Comment by ilya-g** [comment]
I agree with @JakeWharton, if you want to author a KEEP proposal for the standard library API, please try to follow this [template](https://github.com/Kotlin/KEEP/blob/master/proposals/stdlib/TEMPLATE.md).

This discussion about the naming could be moved to youtrack (http://kotl.in/issue), if there are still unanswered questions.

**Comment by mutexkid** [comment]
Thanks @ilya-g for the insight on the KEEP process. Apologies for posting via the wrong channel - i didn’t realize this was the incorrect spot.
One thought: I think it may save time to call out what belongs in a Kotlin Evolution and Enhancement Process proposal (or elsewhere) so that we wind up reporting suggestions in the correct place. Is it possible to update the Readme to include a definition of what does/doesn’t belong here? Also, the template you linked - this may be helpful to include in the guide for how to submit a KEEP. Thank you again for your work!
