### ISSUE TITLE
@Parcelize: Android Studio complains that annotated class is missing CREATOR field

### ISSUE THREAD

**Issue by autonomousapps** [Kotlin/KEEP#83]
Android Studio 3.0 Beta 4
Kotlin plugin 1.1.4-release-Studio3.0-3

I'm my `build.gradle` I have:
```
apply plugin: "org.jetbrains.kotlin.android.extensions"
androidExtensions {
    experimental = true
}
```
And in a Kotlin class:
```
@Parcelize
data class SomeObject(val aParcelableObject: AParcelableObject) : Parcelable
```
`SomeObject` has the red squigglies beneath it and error text: "This class implements Parcelable but does not provide a CREATOR field"

I tried adding a custom Parceler, but (1) it didn't help and (2) seemed to run contrary to my goal of reducing boilerplate.

**Comment by cypressious** [comment]
That's a bug: https://youtrack.jetbrains.com/issue/KT-19300. Please report issues on Youtrack and not in this repo.

**Comment by autonomousapps** [comment]
Thanks for the heads-up! (and the link). Will do.
