### ISSUE TITLE
Embedded Types

### ISSUE THREAD

**Issue by raderio** [Kotlin/KEEP#84]
## Motivation

```kotlin
class Product(val title: String, val description: String)
class Electronics(title: String, description: String, val memory: Long) : Product(title, description)
class Clothing(title: String, description: String, val size: Long) : Product(title, description)
```
Everytime when we inherit from a class, you nee to duplicate this 
`title: String, description: String` in child constructor

## The proposal
I propose to introduce _Embedded Types_
Something like [embedding in golang](https://golang.org/doc/effective_go.html#embedding)

## Implementation
Add `@Embed` annotation 
Syntax 1
```kotlin
class Clothing(val size: Long) : @Embed Product
```
Syntax 2
```kotlin
class Clothing(@Embed product: Product, val size: Long)
```
In second case, user can pass a _Product_ instance, or he can pass _title_ and _description_ beside _size_

Will be transformed to 
```kotlin
class Clothing(title: String, description: String, val size: Long) : Product(title, description)
```

**Comment by guenhter** [comment]
@raderio what if the embedded class has more than one constructor? Just use the primary constructor?

**Comment by raderio** [comment]
You can embed only if class has one constructor

**Comment by yole** [comment]
If you want to suggest a language feature for Kotlin, please file a YouTrack issue. The KEEP project is intended for tracking complete specifications of proposed language features. "Something like embedding in golang" is unfortunately not a specification.

**Comment by yole** [comment]
See also https://github.com/Kotlin/KEEP#how-to-propose
