### ISSUE TITLE
Verify Error for Android Api 19.

### ISSUE THREAD

**Issue by GitHubMurt** [Kotlin/KEEP#91]
Code below works on Api above 19.
Tested on api 19 kitkat, Samsung GT-l9195, doesnt work either on emulator api 19.

Crash code:

> Process: app.pck.name, PID: 2746
> java.lang.VerifyError: app.pck.name/model/Damage$Creator
> at app.pck.name.model.Damage.<clinit>(Damage.kt)
> at java.lang.Class.getDeclaredConstructors(Native Method)
> at java.lang.Class.getDeclaredConstructors(Class.java:574)
> at com.fasterxml.jackson.databind.util.ClassUtil.getConstructors(ClassUtil.java:1114)
> at com.fasterxml.jackson.databind.introspect.AnnotatedCreatorCollector._findPotentialConstructors(AnnotatedCreatorCollector.java:101)
> at com.fasterxml.jackson.databind.introspect.AnnotatedCreatorCollector.collect(AnnotatedCreatorCollector.java:56)

```
@Parcelize
@JsonIgnoreProperties(ignoreUnknown = true)
class Damage @JsonCreator constructor(
        @JsonProperty("eventDate") var date: Date = Date(),
        @JsonProperty("eventHour") var time: String = "",
        @JsonProperty("eventDescription") var description: String? = "",
        @Nullable @JsonProperty("status") var status: EnumStatus? = EnumStatus.REPORTED,
        @JsonProperty("eventType") var eventType: EnumCircumstances = EnumCircumstances.OTHER,
        @Nullable @JsonProperty("carRepairShop") var service: CarService? = null,
        @JsonProperty("processed") var processed: Boolean = false) : Parcelable
```

**Comment by JakeWharton** [comment]
Use http://kotl.in/issue. This forum is for language enhancement discussion only.

**Comment by GitHubMurt** [comment]
Done. For interested: https://youtrack.jetbrains.com/issue/KT-20928
