### ISSUE TITLE
[Feature Request] Extending the Kotlin Data Class for use with JPA

### ISSUE THREAD

**Issue by oleersoy** [Kotlin/KEEP#93]
I documented the concept in [this SO post](https://stackoverflow.com/questions/46838256/extending-the-kotlin-data-class-for-use-with-jpa).

To summarize the idea is to create the simplest possible implementation for equals() and hashcode() usage in the context of JPA that just works all the time without having to read through a myriad of articles and best practices for designing equals() and hashcode() methods.

**Comment by JakeWharton** [comment]
See https://github.com/Kotlin/KEEP/blob/master/README.md#how-to-propose. GitHub issues are not the place for this unless you have a detailed proposal in the correct format to submit.

**Comment by oleersoy** [comment]
Thanks for the heads up.  I'll check out the channels suggested.
