### ISSUE TITLE
Provide JSR-310 / Java8 date-handling for every platform

### ISSUE THREAD

**Issue by fab1an** [Kotlin/KEEP#94]
The Java8 date/time-handling library is probably the best out there.
There exists an exact port for JavaScript: https://js-joda.github.io/js-joda/
If there are no license issues, I think kotlin should include this API out of the box on every platform.

**Comment by udalov** [comment]
KEEP is only used for specific language proposals (see ["How to propose"](https://github.com/Kotlin/KEEP#how-to-propose)). Please file this request as a [YouTrack issue](http://kotl.in/issue) instead.

**Comment by fab1an** [comment]
Issue: https://youtrack.jetbrains.com/issue/KT-21585
