### ISSUE TITLE
Parcelize toghother with inheritance.

### ISSUE THREAD

**Issue by GitHubMurt** [Kotlin/KEEP#97]
Hey, I'm unable to create generic structure togother with @Parcelize annotation.
I want constructor to be used as construcor for Jason, Room, and Parcelable.

Lets assume we have class
```
@Parcelize
class Food(var taste: String = "")
```

Now two solution that come to my mind at first
1.complains that taste have to be var or val, to have usable Parceable constructor
```
@Parcelize
class FastFood(var callory:String = "", taste: String): Food(taste) // error
```

2.complains that I have to explicitly ovveride taste - so what are benefits from polymorphism?
```
@Parcelize
class FastFood(var callory: String = "", var taste: String): Food(taste) // error
```

How can I use efficiently inheritance together with your library?

**Comment by udalov** [comment]
KEEP is only used for language proposals, not issues with the already implemented features (see [the README](https://github.com/Kotlin/KEEP)). Please file a [YouTrack issue](http://kotl.in/issue) instead.

**Comment by GitHubMurt** [comment]
thx,
https://youtrack.jetbrains.com/issue/KT-22139
